<@php

namespace Config;

use Nuhsait\Ci4SimpleAuth\Config\SimpleAuth as BaseSimpleAuth;

/**
 * Generated by php spark simpleauth:setup on <?= $date ?>.
 *
 * $fields, $loginField and $identityCountry are tied to the database schema.
 * Run setup again from scratch to change them.
 * $hashCost, $maxAttempts, $cooldownMinutes and $realm can be edited by hand.
 */
class SimpleAuth extends BaseSimpleAuth
{
    public array $fields = [
<?php foreach ($fields as $field => $options): ?>
        '<?= $field ?>' => ['nullable' => <?= $options['nullable'] ? 'true' : 'false' ?>, 'length' => <?= $options['length'] ?>],
<?php endforeach ?>
    ];

    public string $loginField = '<?= $loginField ?>';

    public ?string $identityCountry = <?= $identityCountry === null ? 'null' : "'" . $identityCountry . "'" ?>;

    public int $hashCost = <?= $hashCost ?>;

    public int $maxAttempts = <?= $maxAttempts ?>;

    public int $cooldownMinutes = <?= $cooldownMinutes ?>;
}
