<@php

namespace <?= $namespace ?>\Database\Migrations;

use CodeIgniter\Database\Migration;

/**
 * Generated by php spark simpleauth:setup on <?= $date ?>.
 */
class CreateAuthUserTable extends Migration
{
    public function up()
    {
        $this->forge->addField([
            'id' => [
                'type'           => 'INT',
                'unsigned'       => true,
                'auto_increment' => true,
            ],
            'name' => [
                'type'       => 'VARCHAR',
                'constraint' => 64,
                'null'       => false,
            ],
<?php foreach ($fields as $field => $options): ?>
            '<?= $field ?>' => [
                'type'       => 'VARCHAR',
                'constraint' => <?= $options['length'] ?>,
                'null'       => <?= $options['nullable'] ? 'true' : 'false' ?>,
            ],
<?php endforeach ?>
            'password_hash' => [
                'type'       => 'VARCHAR',
                'constraint' => 60,
                'null'       => false,
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'null' => true,
            ],
            'updated_at' => [
                'type' => 'DATETIME',
                'null' => true,
            ],
        ]);
        $this->forge->addPrimaryKey('id');
<?php foreach (array_keys($fields) as $field): ?>
        $this->forge->addUniqueKey('<?= $field ?>');
<?php endforeach ?>
        $this->forge->createTable('<?= $table ?>');
    }

    public function down()
    {
        $this->forge->dropTable('<?= $table ?>');
    }
}
