<?php

namespace Nuhsait\Ci4SimpleAuth\Config;

use CodeIgniter\Config\BaseConfig;
use RuntimeException;

/**
 * Package default config.
 *
 * The real values come from app/Config/SimpleAuth.php, generated by
 * `php spark simpleauth:setup`, which extends this class.
 */
class SimpleAuth extends BaseConfig
{
    /**
     * Identity fields selected during setup.
     *
     * @var array<string, array{nullable: bool, length: int}>
     */
    public array $fields = [];

    /**
     * Field used as the username in Basic Auth.
     */
    public string $loginField = '';

    /**
     * Country code of the identity_number field (e.g. 'tr').
     */
    public ?string $identityCountry = null;

    /**
     * bcrypt cost.
     */
    public int $hashCost = 12;

    /**
     * Failed attempts allowed within the cooldown window.
     */
    public int $maxAttempts = 5;

    /**
     * Failed attempt window and lock duration, in minutes.
     */
    public int $cooldownMinutes = 15;

    /**
     * Realm sent in the WWW-Authenticate header.
     */
    public string $realm = 'SimpleAuth';

    /**
     * Throws a meaningful error if setup has not been run.
     */
    public function assertConfigured(): void
    {
        if ($this->fields === [] || $this->loginField === '') {
            throw new RuntimeException('SimpleAuth is not configured. Run "php spark simpleauth:setup" first.');
        }
    }
}
